users:
  - email: account@gmail.com
    password: account_pass
    schedule_id: 99999999  # Find schedule_id in re-schedule page link https://ais.usvisa-info.com/en-am/niv/schedule/{SCHEDULE_ID}/appointment
    group_id: 99999999  # Find schedule_id in re-schedule page link https://ais.usvisa-info.com/en-am/niv/schedule/{SCHEDULE_ID}/appointment
  - email: account2@gmail.com
    password: account_pass2
    schedule_id: 88888888
    group_id: 88888888

period_start: 2023-03-20
perido_end: 2023-06-01
# Change "en-am-yer", based on your embassy Abbreviation in embassy.py list.

embassies:
  - country_code: en-il
    facility_id: 96 # Tel Aviv
    continue: 'Continue'
  - country_code: en-il
    facility_id: 97 # Jerusalem

chrome_driver:
  local_use: True
  hub_address: http://localhost:9515/wd/hub  # HUB_ADDRESS is mandatory only when LOCAL_USE = False

telegram:
  bot_token: some_token
  chat_id: 123456789
  message_thread_id: null

time:
  retry_lower_bound: 10
  retry_upper_bound: 120
  work_limit_hours: 1.5
  work_cooldown_hours: 2.25
  ban_cooldown_hours: 5
