users:
  - email: test@mail.ru
    password: 'test-test-test'
    schedule_id: 12345678
    group_id: 12345678
    applicants: 1

embassies:
  - country_code: en-fr
    continue: 'Continue'
    elements:
      - location_xpath: '//*[@id="paymentOptions"]/div[2]/table/tbody/tr/td[1]'
        status_xpath: '//*[@id="paymentOptions"]/div[2]/table/tbody/tr/td[2]'

chrome_driver:
  local_use: True
  hub_address: http://localhost:9515/wd/hub  # HUB_ADDRESS is mandatory only when LOCAL_USE = False

telegram:
  bot_token: 1111111111:testtesttesttesttesttest
  chat_id: -1111111111111
  thread_id: null
  msg_prefix: 'France'

time:
  retry_lower_bound: 150
  retry_upper_bound: 200
  work_limit_hours: 2.0
  work_cooldown_hours: 0.25
  ban_cooldown_hours: 0.01
